<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="aNummersAanvraag-v1.1.wsdl"
                  targetNamespace="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr-v1.1"
                  xmlns:anr="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr-v1.1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xs:schema>
            <xs:import schemaLocation="aNummersAanvraag-v1.1.xsd"
                       namespace="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr-v1.1"/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="aNummersAanvraag">
        <wsdl:part name="aanvraag" element="anr:aNummersAanvraag"/>
    </wsdl:message>
    <wsdl:message name="aNummersAntwoord">
        <wsdl:part name="antwoord" element="anr:aNummersAntwoord"/>
    </wsdl:message>

    <wsdl:portType name="VraagVoorraadAnrInterface">
        <wsdl:operation name="getANummers">
            <wsdl:input wsaw:Action="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr"
                        name="aNummersAanvraag" message="anr:aNummersAanvraag"/>
            <wsdl:output wsaw:Action="www.rvig.nl/GBA/GBA-V/aNummersAntwoord"
                         name="aNummersAntwoord" message="anr:aNummersAntwoord"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="VraagVoorraadAnrBinding" type="anr:VraagVoorraadAnrInterface">
        <wsaw:UsingAddressing wsdl:required="true"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="getANummers">
            <soap:operation soapAction="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr/getANummers"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="VraagVoorraadAnrService">
        <wsdl:port name="VraagVoorraadAnrPort" binding="anr:VraagVoorraadAnrBinding">
            <soap:address location="http://www.rvig.nl/GBA/GBA-V/VraagVoorraadAnr"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
